---
abstract: 'ANSI-colored text renderer for Perl6::Perldoc'
author:
  - 'Hinrik Örn Sigurðsson, L<hinrik.sig@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Perldoc-To-Ansi
no_index:
  directory:
    - inc
requires:
  Perl6::Perldoc: 0.0.5
version: 0.02
